config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :schedules
  root 'schedules#show'

  get '/schedules/create_draft/new' => 'schedules#select_users', as: 'select_draft'
  get '/schedules/:schedule_id/draft' => 'schedules#draft', as: 'new_draft'
  put '/schedules/:schedule_id/draft' => 'schedules#edit', as: 'edit_draft'
  post '/schedules/create_draft' => 'schedules#new', as: 'draft_lobby_path'
  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create'
  delete '/sessions' => 'sessions#destroy', as: 'destroy_session'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
	has_many :tasks
end

app/models/drafter.rb
class Drafter < ApplicationRecord
  belongs_to :user
  belongs_to :schedule

end

app/models/group.rb
class Group < ApplicationRecord
	has_many :tasks
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  has_many :selections
  has_many :users, through: :selections
  has_many :tasks, through: :selections
  has_many :drafters

  def find_selection(args)
    self.selections.select { |selection| selection.day.id == args[:day_id] && selection.group.id == args[:group_id]}
  end
end

app/models/selection.rb
class Selection < ApplicationRecord
	belongs_to :schedule
	belongs_to :user
	belongs_to :task
	has_one :day, through: :task
  has_one :group, through: :task
end

app/models/task.rb
class Task < ApplicationRecord
	has_many :selections
	belongs_to :day
	belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
	has_many :selections
	has_many :schedules, through: :selections
	has_many :tasks, through: :selections
	has_many :groups, through: :tasks
  has_many :drafters
  has_secure_password

	validates :email, format: { with: /\b+@divebookscamp\.com\z/,
                  message: "must be a valid Dive Books Camp account" }
	validates_uniqueness_of :email

	def ordered_choices(schedule)
	  user_selections = self.selections.where(schedule_id: schedule.id)
		ordered_selections = user_selections.map {|sel| sel}.sort {|a, b| a.day.id <=> b.day.id}
		return ordered_selections
	end

	def percent_time_in(schedule, group_id)
		user_selections = self.selections.where(schedule_id: schedule.id)
		occurences_of_group_selections = user_selections.select { |selection| selection.group.id == group_id}
		return (occurences_of_group_selections.count / 15.0 * 100).round(1)
	end

	def total_days_off
		user_selections = self.selections
		days_off = user_selections.select {|selection| selection.group.id == 6}
		return days_off.count
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to new_session_path unless current_user
  end

  def logged_in?
    if session[:user_id]
      return true
    else
      return false
    end
  end


  private

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to new_session_path # halts request cycle
    end
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
skip_before_action :verify_authenticity_token, :only => [:new]

  def show
    @schedule = Schedule.last
    render 'show'
  end

  def select_users
    @users ||= User.all
    @draftlist = @users
    render 'drafts/select_users'
  end

  def new
    @schedule = Schedule.create(start_date: params[:start_date])
    @users = []
    params[:users].each do |value|
      @users << User.find(value.to_i)
    end
    @users.shuffle!
    @snaked_users = @users + @users.reverse
    @drafters = @snaked_users.map do |user|
      Drafter.create(user_id: user.id, schedule_id: @schedule.id)
    end


    redirect_to new_draft_path(@schedule)
  end

  def edit
    @schedule = Schedule.find(params[:schedule_id])
    @selection = Selection.new(user_id: session[:user_id], schedule_id: @schedule.id, task_id: params[:id_to_update])
    current_drafter = @schedule.drafters.order(:id).first

    if request.xhr?
      if @selection.save
        Drafter.create(user_id: session[:user_id], schedule_id: @schedule.id)
        current_drafter.destroy
        @schedule = Schedule.find(params[:schedule_id])
        current_drafter = @schedule.drafters.order(:id).first
        if current_drafter.user_id == current_user.id
          render 'schedules/_links_show', layout: false, locals: {schedule: @schedule}
        else
          render 'schedules/_no_links_show', layout: false, locals: {schedule: @schedule}
        end
      else
        if current_drafter.user_id == current_user.id
          render  '/schedules/_links_show', layout: false, locals: { schedule: @schedule }
        else
          render 'schedules/_no_links_show', layout: false, locals: {schedule: @schedule}
        end
      end
    else
      "booo"
    end
  end

  def draft
    @schedule = Schedule.find(params[:schedule_id])
    current_drafter = @schedule.drafters.order(:id).first
    p current_drafter
    if current_drafter.user_id == current_user.id
      render 'schedules/edit'
    else
      render 'schedules/edit_no_links'
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
before_filter :require_login, :except => [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: session_params[:email]).try(:authenticate, session_params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:notice] = "Invalid email/password. Please try again."
      render 'new'
    end
  end

  def destroy
    p "this got here"
    session[:user_id] = nil
    redirect_to root_path
  end

private

  def session_params
    params.require(:session).permit(:email, :password)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :require_login, :except => [:new, :create]

  def show
    @user = User.find(params[:id])
    @schedule = Schedule.last
    @week = Day.all.limit(5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
      session[:user_id] = @user.id
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find([params:id])
    @user.destroy

    #WHERE SHOULD THIS REDIRECT TO?
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  
end

app/views/drafts/select_users.html.erb
<form action = '/schedules/create_draft' method="post">
<!-- <select id="start_date_year" name="start_date[year]">
  <option value="1">Lisbon</option>
  <option value="2">Madrid</option>
  <option value="12">Berlin</option>
</select> -->
<!-- <select id="start_date_month" name="start_date[month]">Month </select>
<select id="start_date_day" name="start_date[day]"> ... </select></br> -->

  Start Date:
  <input type="date" name="start_date"></br>

<% @draftlist.each do |user| %>
  <input type="checkbox" name="users[<%= user.id %>]" value="<%= user.id %>"><%= user.first_name %><br>
<% end %>
  <input type="submit" value="Submit">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiveBooksCamp Scheduler</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag "application" %>
  </head>
  <header>
    <nav>
      <ul>
        <li class="btn btn-default"><%= link_to_unless(current_user, "Register", new_user_path)  do
          link_to('Logout', destroy_session_path, method: :delete)
        end %></li>
        <li class="btn btn-default"> <%= link_to_if(current_user, "Profile", current_user) do
         end%></li>
         <li class="btn btn-default"> <%= link_to_if(current_user, "Create Draft", select_draft_path) do end%></li>
         <% @schedule = Schedule.last %>
         <li class="btn btn-default"><%= link_to_if(current_user, "Join Draft", new_draft_path(@schedule.id)) do end %></li>
         <li class="btn btn-default"><%= link_to_if(current_user, "Home", schedule_path(@schedule)) do end %></li>

      </ul>
    </nav>

  </header>

  <body>
    <main class="container">
      <%= notice %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/schedules/_links_show.html.erb
<div>
  <ul>
    <% schedule.drafters.order(:id).each do |drafter| %>
      <li><%= drafter.user.first_name %></li>
    <% end %>
  </ul>
  <div  class="tabs row">
    <div class="col-md-10">
      <ul class="tab-links">
      <li class="active"><a href="#week-1">Week 1</a></li>
      <li><a href="#week-2">Week 2</a></li>
      <li><a href="#week-3">Week 3</a></li>
    </ul>

    <div class="tab-content" id="week-1" style="display: block">
      <table class="table table-bordered">
        <tr>
          <th>Week 1</th>
          <th>Monday</th>
          <th>Tuesday</th>
          <th>Wednesday</th>
          <th>Thursday</th>
          <th>Friday</th>
        </tr>
        <tr>
          <td>Group 1</td>
          <% (1..5).each do |i| %>
            <% selection = @schedule.find_selection(group_id: 1, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td id=<%= "#{i}" %> class="clickable"></td>
            <% end %>
          <% end %>
        </tr>
        <tr>
          <td>Group 2</td>
          <% (1..5).each do |i| %>
            <% selection = @schedule.find_selection(group_id: 2, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td id=<%= "#{i+5}" %> class="clickable"></td>
            <% end %>
          <% end %>
        </tr>
        <tr>
          <td>Group 3</td>
          <% (1..5).each do |i| %>
            <% selection = @schedule.find_selection(group_id: 3, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td id=<%= "#{i+10}" %> class="clickable"></td>
            <% end %>
          <% end %>
        </tr>
        <tr>
          <td>Runner</td>
         <% (1..5).each do |i| %>
            <% selection = @schedule.find_selection(group_id: 4, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
          <% end %>
        </tr>
        <tr>
          <td>Maintenance</td>
         <% (1..5).each do |i| %>
            <% selection = @schedule.find_selection(group_id: 5, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
          <% end %>
        </tr>
        <tr>
        <td>Off</td>
         <% (1..5).each do |i| %>
          <% selection = @schedule.find_selection(group_id: 6, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
          <% end %>
        </tr>
      </table>
    </div>

    <div class="tab-content" id="week-2" >
      <table class="table table-bordered">
        <tr>
          <th>Week 2</th>
          <th>Monday</th>
          <th>Tuesday</th>
          <th>Wednesday</th>
          <th>Thursday</th>
          <th>Friday</th>
        </tr>
        <tr>
          <td>Group 1</td>
          <% (6..10).each do |i| %>
            <% selection = @schedule.find_selection(group_id: 1, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td id=<%= "#{i + 15}" %> class="clickable"></td>
            <% end %>
          <% end %>
        </tr>
        <tr>
          <td>Group 2</td>
          <% (6..10).each do |i| %>
            <% selection = @schedule.find_selection(group_id: 2, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td id=<%= "#{i + 20}" %> class="clickable"></td>
            <% end %>
          <% end %>
        </tr>
        <tr>
          <td>Group 3</td>
          <% (6..10).each do |i| %>
            <% selection = @schedule.find_selection(group_id: 3, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td id=<%= "#{i + 25}" %> class="clickable"></td>
            <% end %>
          <% end %>
        </tr>
        <tr>
          <td>Runner</td>
         <% (6..10).each do |i| %>
            <% selection = @schedule.find_selection(group_id: 4, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
          <% end %>
        </tr>
        <tr>
          <td>Maintenance</td>
         <% (6..10).each do |i| %>
            <% selection = @schedule.find_selection(group_id: 5, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
          <% end %>
        </tr>
          <tr>
            <td>Off</td>
           <% (6..10).each do |i| %>
              <% selection = @schedule.find_selection(group_id: 6, day_id: i).first %>
              <% if selection %>
                <td><%= selection.user.first_name %></td>
              <% else %>
                <td></td>
              <% end %>
            <% end %>
          </tr>
        </table>
      </div>

      <div class="tab-content" id="week-3">
        <table class="table table-bordered">
          <tr>
            <th>Week 3</th>
            <th>Monday</th>
            <th>Tuesday</th>
            <th>Wednesday</th>
            <th>Thursday</th>
            <th>Friday</th>
          </tr>
          <tr>
            <td>Group 1</td>
            <% (11..15).each do |i| %>
              <% selection = @schedule.find_selection(group_id: 1, day_id: i).first %>
              <% if selection %>
                <td><%= selection.user.first_name %></td>
              <% else %>
                <td id=<%= "#{i + 30}" %> class="clickable"></td>
              <% end %>
            <% end %>
          </tr>
          <tr>
            <td>Group 2</td>
            <% (11..15).each do |i| %>
              <% selection = @schedule.find_selection(group_id: 2, day_id: i).first %>
              <% if selection %>
                <td><%= selection.user.first_name %></td>
              <% else %>
                <td id=<%= "#{i + 35}" %> class="clickable"></td>
              <% end %>
            <% end %>
          </tr>
          <tr>
            <td>Group 3</td>
            <% (11..15).each do |i| %>
              <% selection = @schedule.find_selection(group_id: 3, day_id: i).first %>
              <% if selection %>
                <td><%= selection.user.first_name %></td>
              <% else %>
                <td id=<%= "#{i + 40}" %> class="clickable"></td>
              <% end %>
            <% end %>
          </tr>
          <tr>
            <td>Runner</td>
           <% (11..15).each do |i| %>
              <% selection = @schedule.find_selection(group_id: 4, day_id: i).first %>
              <% if selection %>
                <td><%= selection.user.first_name %></td>
              <% else %>
                <td></td>
              <% end %>
            <% end %>
          </tr>
          <tr>
            <td>Maintenance</td>
           <% (11..15).each do |i| %>
              <% selection = @schedule.find_selection(group_id: 5, day_id: i).first %>
              <% if selection %>
                <td><%= selection.user.first_name %></td>
              <% else %>
                <td></td>
              <% end %>
            <% end %>
          </tr>
          <tr>
            <td>Off</td>
           <% (11..15).each do |i| %>
              <% selection = @schedule.find_selection(group_id: 6, day_id: i).first %>
              <% if selection %>
                <td><%= selection.user.first_name %></td>
              <% else %>
                <td></td>
              <% end %>
            <% end %>
          </tr>
        </table>
      </div>
    </div>
    <div class="sidebar col-sm-2">
      <ul>
        <li><%= image_tag "Dexter.jpg" %> Zaki A</li><br>
        <li><%= image_tag "Lisa.jpg" %> Adam B </li><br>
        <li><%= image_tag "Bunny.jpg" %> Max G </li><br>
        <li><%= image_tag "Karl.jpg" %> Dumitru G</li><br>
        <li><%= image_tag "Doggy.jpg" %>Doug J </li><br>
        <li><%= image_tag "Dexter.jpg" %> Inc. </li><br>
      </ul>
    </div>
  </div>
</div>

app/views/schedules/_no_links_show.html.erb
<ul>
  <% @schedule.drafters.order(:id).each do |drafter| %>
    <li><%= drafter.user.first_name %></li>
  <% end %>
</ul>

<div class="tabs row">
  <div class="col-md-10">
    <ul class="tab-links">
    <li class="active"><a href="#week-1">Week 1</a></li>
    <li><a href="#week-2">Week 2</a></li>
    <li><a href="#week-3">Week 3</a></li>
  </ul>

  <div class="tab-content" id="week-1" style="display: block">
    <table class="table table-bordered">
      <tr>
        <th>Week 1</th>
        <th>Monday</th>
        <th>Tuesday</th>
        <th>Wednesday</th>
        <th>Thursday</th>
        <th>Friday</th>
      </tr>
      <tr>
        <td>Group 1</td>
        <% (1..5).each do |i| %>
          <% selection = @schedule.find_selection(group_id: 1, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
        <% end %>
      </tr>
      <tr>
        <td>Group 2</td>
        <% (1..5).each do |i| %>
          <% selection = @schedule.find_selection(group_id: 2, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
        <% end %>
      </tr>
      <tr>
        <td>Group 3</td>
        <% (1..5).each do |i| %>
          <% selection = @schedule.find_selection(group_id: 3, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
        <% end %>
      </tr>
      <tr>
        <td>Runner</td>
       <% (1..5).each do |i| %>
          <% selection = @schedule.find_selection(group_id: 4, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
        <% end %>
      </tr>
      <tr>
        <td>Maintenance</td>
       <% (1..5).each do |i| %>
          <% selection = @schedule.find_selection(group_id: 5, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
        <% end %>
      </tr>
      <tr>
        <td>Off</td>
       <% (1..5).each do |i| %>
          <% selection = @schedule.find_selection(group_id: 6, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
        <% end %>
      </tr>
    </table>
  </div>
  <div class="tab-content" id="week-2" >
    <table class="table table-bordered">
      <tr>
        <th>Week 2</th>
        <th>Monday</th>
        <th>Tuesday</th>
        <th>Wednesday</th>
        <th>Thursday</th>
        <th>Friday</th>
      </tr>
      <tr>
        <td>Group 1</td>
        <% (6..10).each do |i| %>
          <% selection = @schedule.find_selection(group_id: 1, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
        <% end %>
      </tr>
      <tr>
        <td>Group 2</td>
        <% (6..10).each do |i| %>
          <% selection = @schedule.find_selection(group_id: 2, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
        <% end %>
      </tr>
      <tr>
        <td>Group 3</td>
        <% (6..10).each do |i| %>
          <% selection = @schedule.find_selection(group_id: 3, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
        <% end %>
      </tr>
      <tr>
        <td>Runner</td>
       <% (6..10).each do |i| %>
          <% selection = @schedule.find_selection(group_id: 4, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
        <% end %>
      </tr>
      <tr>
        <td>Maintenance</td>
       <% (6..10).each do |i| %>
          <% selection = @schedule.find_selection(group_id: 5, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
        <% end %>
      </tr>
      <tr>
        <td>Off</td>
       <% (6..10).each do |i| %>
          <% selection = @schedule.find_selection(group_id: 6, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
        <% end %>
      </tr>
    </table>
  </div>
  <div class="tab-content" id="week-3">
    <table class="table table-bordered">
      <tr>
        <th>Week 3</th>
        <th>Monday</th>
        <th>Tuesday</th>
        <th>Wednesday</th>
        <th>Thursday</th>
        <th>Friday</th>
      </tr>
      <tr>
        <td>Group 1</td>
        <% (11..15).each do |i| %>
          <% selection = @schedule.find_selection(group_id: 1, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
        <% end %>
      </tr>
      <tr>
        <td>Group 2</td>
        <% (11..15).each do |i| %>
          <% selection = @schedule.find_selection(group_id: 2, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
        <% end %>
      </tr>
      <tr>
        <td>Group 3</td>
        <% (11..15).each do |i| %>
          <% selection = @schedule.find_selection(group_id: 3, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
        <% end %>
      </tr>
      <tr>
        <td>Runner</td>
       <% (11..15).each do |i| %>
          <% selection = @schedule.find_selection(group_id: 4, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
        <% end %>
      </tr>
      <tr>
        <td>Maintenance</td>
       <% (11..15).each do |i| %>
          <% selection = @schedule.find_selection(group_id: 5, day_id: i).first %>
            <% if selection %>
              <td><%= selection.user.first_name %></td>
            <% else %>
              <td></td>
            <% end %>
        <% end %>
      </tr>
      <tr>
        <td>Off</td>
       <% (11..15).each do |i| %>
          <% selection = @schedule.find_selection(group_id: 6, day_id: i).first %>
          <% if selection %>
            <td><%= selection.user.first_name %></td>
          <% else %>
            <td></td>
          <% end %>
        <% end %>
      </tr>
    </table>
  </div>
  <div class="sidebar col-sm-2">
    <ul>
      <li><%= image_tag "Dexter.jpg" %> Zaki A</li><br>
      <li><%= image_tag "Lisa.jpg" %> Adam B </li><br>
      <li><%= image_tag "Bunny.jpg" %> Max G </li><br>
      <li><%= image_tag "Karl.jpg" %> Dumitru G</li><br>
      <li><%= image_tag "Doggy.jpg" %>Doug J </li><br>
      <li><%= image_tag "Dexter.jpg" %> Inc. </li><br>
    </ul>
  </div>
</div>

app/views/schedules/edit.html.erb
<h1>INSTRUCTOR SCHEDULE - STARTING: <%= @schedule.start_date %></h1>
<h3>Draft Order</h3>

<div class="links-partial">
<script type="text/javascript">
  refresh_page()
</script>
  <%= render partial: "links_show", locals: {schedule: @schedule}, layout: false %>
</div>

app/views/schedules/edit_no_links.html.erb
<h1>INSTRUCTOR SCHEDULE - STARTING: <%= @schedule.start_date %></h1>
<h3>Draft Order</h3>

<div class="links-partial">
<script type="text/javascript">
  refresh_page()
</script>
  <%= render partial: "no_links_show", locals: {schedule: @schedule}, layout: false %>
</div>

app/views/schedules/new.html.erb
<ul>
  <% @drafters.each do |drafter| %>
    <li><%= drafter.user.first_name %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Create User</h1>

<div class="register-form">
  <%= bootstrap_form_for(@user, inline_errors: true, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
    <% if @user.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@user.errors.count, "error") %> prevented this user from saving</h2>
        <ul>
          <% @user.errors.full_messages.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.text_field :first_name %><br>
    <%= f.text_field :last_name %><br>
    <%= f.email_field :email %><br>
    <%= f.password_field :password %><br>
    <div class="submit"><%= f.form_group do %></div>
      <%= f.submit "Create Account", class: "btn btn-info"%>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<h2 class="section-title"><%= @user.first_name %> <%= @user.last_name%> </h2>

<div id="current-session-user-schedule">
  <h3>Current Session:</h3>
    <table class="table table-bordered" >
      <thead class="thead-inverse">
        <tr>
          <th colspan="1"></th>
        <% @week.each do |day| %>
          <th><%= day.name %></th>
        <% end  %>
      </tr>

      <tr>
        <th scope="row">Week 1</th>
        <% @user.ordered_choices(@schedule)[0..4].each do | selection|%>
        <td>
          <%= selection.group.name %>
        </td>
          <% end %>
      </tr>

      <tr>
        <th scope="row">Week 2</th>
        <% if @user.ordered_choices(@schedule).length > 5 %>
         <% @user.ordered_choices(@schedule)[5..9].each do | selection| %>
          <td>
            <%= selection.group.name %>
          </td>
          <% end %>
        <% end %>
      </tr>

      <tr>
        <th scope="row">Week 3</th>
        <% if @user.ordered_choices(@schedule).length > 10 %>
          <% @user.ordered_choices(@schedule)[10..14].each do | selection|%>
          <td>
            <%= selection.group.name %>
          </td>
          <% end %>
        <% end %>
      </tr>
    </tbody>
  </table>
  </div>

<div id="user-percentages-list">
  <h3>Time spent this session:</h3>
  <table class="table table-sm">
    <thead>
      <tr>
        <th></th>
        <th>Group 1</th>
        <th>Group 2</th>
        <th>Group 3</th>
        <th>Running</th>
        <th>Maintenance</th>
        <th>Off</th>
      </tr>
    </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td><%= @user.percent_time_in(@schedule, 1) %>%</td>
      <td><%= @user.percent_time_in(@schedule, 2) %>%</td>
      <td><%= @user.percent_time_in(@schedule, 3) %>%</td>
      <td><%= @user.percent_time_in(@schedule, 4) %>%</td>
      <td><%= @user.percent_time_in(@schedule, 5) %> %</td>
      <td><%= @user.percent_time_in(@schedule, 6) %> %</td>
    </tr>
  </tbody>
</table>
<h3>Total Off Days: <%= @user.total_days_off %></h3>

</div>